### PR TITLE
[scripts] Add script to convert joint_trajectory messages to multi_do…

### PR DESCRIPTION
**Pull request by AnaBatinovic**
Hi, I added a script to convert joint_trajectory messages to multi_dof_joint_trajectory messages. It is written following the example of similar scripts in the repository.
Best, Ana

### CODE REVIEW

**Comment by fpetric** [comment]
To me, it looks like executing trajectory publisher and flag are not used/needed

**Comment by AnaBatinovic** [comment]
> To me, it looks like executing trajectory publisher and flag are not used/needed

You are right. I will fix that. Thanks!

**Comment by AnaBatinovic** [comment]
After reviewing, I suggest merging the changes with the "squash and merge" option

**Review by aivano — APPROVED** [review]
All good

**Comment by aivano** [comment]
@AnaBatinovic Deleting the devel branch.

**Pull request merged**
